CREATE TABLE IF NOT EXISTS alumnos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento   VARCHAR(10)  NOT NULL,
    numero_documento VARCHAR(20)  NOT NULL UNIQUE,
    nombres          VARCHAR(100) NOT NULL,
    apellidos        VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    correo           VARCHAR(150) UNIQUE,
    telefono         VARCHAR(15),
    estado           VARCHAR(10)  DEFAULT 'ACTIVO'
);
